#!//opt/homebrew/opt/ruby@3.2/bin/ruby

require 'bundler/setup'
require 'colorize'
require 'ruby_figlet'
require 'tempfile'
require 'rspec'
require 'rspec/core/formatters/progress_formatter'
require 'json'

# Determine data directory
if __dir__ == File.expand_path('~/.local/bin')
  DATA_DIR = File.expand_path('../share/rubyprimer', __dir__)
else
  DATA_DIR = __dir__
end

load "#{DATA_DIR}/lib/stringformat.rb"
load "#{DATA_DIR}/lib/sayings.rb"

def print_header(header)
  puts ""
  figlet = RubyFiglet::Figlet.new(header, 'standard')
  figlet_text = figlet.to_s
  max_width = figlet_text.lines.map(&:length).max
  border = "=" * max_width
  puts border
  puts figlet_text.magenta
  puts border
  puts ""
end

def print_subheader(header)
  puts header.underline
end

def print_lesson_name(lesson_name)
  figlet = RubyFiglet::Figlet.new(lesson_name, 'thin')
  puts figlet.to_s.cyan
end

def print_welcome()
  message = <<-WELCOME
Welcome to the Ruby Primer.  This is a console version of the Ruby Primer
previously found at http://rubymonk.com/. This is a program written in `ruby`
that runs actual `ruby` code snippets in the `ruby` interpreter on your system.
It is intended to be interactive, fun, and educational.  Enjoy!
  WELCOME
  puts "\n#{message.format(color:'yellow')}\n\n"
end

def get_input(question)
  print question
  STDOUT.flush
  STDIN.gets.chomp
end

def print_paragraph(para, mod=nil)
  paratext = para.chomp
  if mod
    puts paratext.send(mod)
  else
    puts ""
    puts paratext.format
  end 
  puts ""
end

def print_example(example, test=false, example_id=nil) 
  puts ">>> Example #{example_id} <<<".underline.grey
  puts ""
  print_paragraph(example, "green")
  ans = get_input("Type 'edit' to edit the code in vim, or type 'run' to run the code: ")
  if ans.downcase == "edit"
    puts "Editing code ..."
    edited_code = edit_code(example)
    print_example(edited_code, test, example_id)
  elsif ans.downcase == "run"
    puts "Running code ..."
    if test
      test_code(example, example_id)
    else	    
      run_code(example)
    end
  else
    puts ""
    puts "         ERROR: I'm not sure what you mean by '#{ans}' ... please try again".red
    puts ""
    print_example(example, test, example_id)
  end
end

def get_example(example_id)
  file = File.new("#{DATA_DIR}/examples/#{example_id}.rb", "r")
  contents = file.read
  file.close
  contents
end

def write_code_to_tmpfile(code)
  file = Tempfile.new('rubyprimer')
  ObjectSpace.undefine_finalizer(file)
  file.write(code)
  path = file.path
  file.close
  path
end

def read_file_and_remove(path)
  contents = File.read(path)
  File.unlink(path)
  contents
end

def edit_code(code)
  path = write_code_to_tmpfile(code)
  command = "/usr/bin/vim #{path}"
  pid = spawn(command)
  Process.wait(pid)
  read_file_and_remove(path)
end

def decorate_output(location) 
  if location == "top"
    puts "#### Output: ####".bold.light_green
  elsif location == "bottom"
    puts "#################".bold.light_green 
  end
end

def run_code(code, decorate=true)
  path = write_code_to_tmpfile(code)
  decorate_output("top") unless !decorate
  command = "#{RbConfig.ruby} #{path}"
  pid = spawn(command)
  Process.wait(pid)
  puts "" unless !decorate
  decorate_output("bottom") unless !decorate
  File.unlink(path)
end

def test_code(code, example_id) 
  path = write_code_to_tmpfile(code)
  spec = File.read("#{DATA_DIR}/examples_spec/#{example_id}.rb")
  spec.sub! '__TMPFILE__', path
  test_path = write_code_to_tmpfile(spec)
  decorate_output("top")

  run_code(code, false)

  config = RSpec.configuration
  config.color = true
  RSpec.clear_examples
  status = RSpec::Core::Runner.run([test_path])

  should_rerun = false
  if status == 0
    puts ""
    puts "---> SUCCESS:  #{Sayings.get_saying('happy')}".bold.light_yellow
    puts ""
  else
    puts ""
    puts "---> WHOOPS:  #{Sayings.get_saying('sad')}".bold.light_red
    puts ""
    should_rerun = true
  end
  decorate_output("bottom")

  File.unlink(path)
  File.unlink(test_path)

  if should_rerun
    print_example(get_example(example_id), true, example_id)
  end
end

def press_enter()
  get_input("Press ENTER to continue")
  puts ""
end

def read_json_file(file_name)
  file = File.read(file_name)
  JSON.parse(file)
end

def print_toc
  toc = read_json_file("#{DATA_DIR}/lessons/toc.json")
  entries = []
  toc['lessons'].each do |lesson|
    id = lesson.sub('.json', '')
    lesson_data = read_json_file("lessons/#{lesson}")
    name = lesson_data['name'] || id
    entries << "#{id}: #{name}"
  end
  max_entry_length = entries.map(&:length).max || 0
  width = 8 + max_entry_length
  puts ""
  puts "Table of Contents".center(width).bold.underline
  entries.each do |entry|
    puts "    • #{entry}"
  end
  puts ""
end

def process_toc(lesson_id=nil, start_sub=0)
  toc = read_json_file("#{DATA_DIR}/lessons/toc.json")

  toc['lessons'].each do |lesson_file|
    if lesson_id
      if lesson_file == "#{lesson_id}.json"
        if start_sub > 0
          print_paragraph("\n\nSkipping to lesson: #{lesson_id}, subsection #{start_sub + 1}!")
        else
          print_paragraph("\n\nSkipping to lesson: #{lesson_id}!")
        end
        process_lesson("#{DATA_DIR}/lessons/#{lesson_id}.json", start_sub)
      end
    else
      process_lesson("#{DATA_DIR}/lessons/#{lesson_file}", 0)
    end
  end
end

def process_lesson(lesson_file, start_sub = 0)
  lesson = read_json_file(lesson_file)
  if lesson['number']
    print_lesson_name("Lesson #{lesson['number']}")
  end
  if lesson['name']
    print_header(lesson['name'])
  end
  lesson['subsections'].each_with_index do |subsection, i|
    next if i < start_sub
    print_subheader(subsection['name'])
    subsection['items'].each do |item|
      case item['type']
        when "press_enter"
          press_enter()
	when "paragraph"
          print_paragraph(item['value'])
	when "subheader"
          print_subheader(item['value'])
	when "example"
          print_example(get_example(item['value']), false, item['value'])
	when "test_example"
          print_example(get_example(item['value']), true, item['value'])
      end
    end
  end
end

def main(args)
  if args[0] == "toc"
    print_toc
  else
    arg = args[0]
    if arg =~ /^(\d+\.\d+)\.(\d+)$/
      lesson_id = $1
      sub_num = $2.to_i
      start_sub = sub_num - 1  # 1-based to 0-based
    else
      lesson_id = arg
      start_sub = 0
    end
    print_welcome() if start_sub == 0
    press_enter() if start_sub == 0
    process_toc(lesson_id, start_sub)
  end
end
########################################################
main(ARGV)
